### PR TITLE
Added "immersive" option.

### PR DESCRIPTION
**Pull request by scorpiosixnine**
A boolean flag which suppresses the "XXX wants to…" notifications, as they are a bit immersion-breaking.

### CODE REVIEW

**Comment by lgbtqPP** [comment]
Thanks for the PR!

A small change, rename the `immersion` to `nonotification`, it is not immediately obvious that `immersion` implies that notifications will be disabled.

**Comment by lgbtqPP** [comment]
Actually, I can make the change later. Will merge tonight! Cheers.

**Comment by scorpiosixnine** [comment]
Cool. Sorry for the slow response - this is an alt GitHub account and I tend to forget to check the notifications :)

**Comment by lgbtqPP** [comment]
Closed by ae4a2404fa458d635187f66a169ec2111f8a378e

**Pull request closed without merging**
